# Generated by Django 4.2.5 on 2026-02-07 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_alter_episode_options_alter_image_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='book',
            name='hot',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='book',
            name='id',
            field=models.CharField(db_index=True, max_length=100, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='book',
            name='image_url',
            field=models.URLField(default=''),
        ),
        migrations.AlterField(
            model_name='book',
            name='raw_url',
            field=models.URLField(default=''),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='episode',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='episode',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='pdfs'),
        ),
        migrations.AlterField(
            model_name='episode',
            name='raw_url',
            field=models.URLField(default=''),
        ),
        migrations.AlterField(
            model_name='episode',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='image',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='image',
            name='index',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='image',
            name='raw_url',
            field=models.URLField(default=''),
        ),
        migrations.AddIndex(
            model_name='image',
            index=models.Index(fields=['episode', 'index'], name='apps_image_episode_881336_idx'),
        ),
    ]
